spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j9_ironbank
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  #profiles:
    #active: load-data

server:
  port: 8080