package com.ironhack.ironbank.model.enums;

public enum TransactionType {
    DEPOSIT,WITHDRAW,TRANSFER,PAY_SERVICE,PAY_WITH_CREDIT_CARD,
    CREATE_SAVING_ACCOUNT,
    CREDIT_FROM_TRANSFER, PENALTY, INTERESTS,
    MONTHLY_MAINTENANCE, DEBIT_CREDIT_CARD
}
